package components;

import classes.Ingrediente;

import javax.swing.*;
import java.awt.*;

public class BajaAlergias {
    public JTable tabla;
    public JComboBox<String> cb_alumnos;
    public JComboBox<Ingrediente> cb_alergias;
    public JButton btn_baja;
    public JPanel BajaAlergias;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        BajaAlergias = new JPanel();
        BajaAlergias.setLayout(new GridBagLayout());
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(550, 400));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.BOTH;
        BajaAlergias.add(scrollPane1, gbc);
        tabla = new JTable();
        Font tablaFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, 14, tabla.getFont());
        if (tablaFont != null) tabla.setFont(tablaFont);
        tabla.setPreferredSize(new Dimension(550, 400));
        scrollPane1.setViewportView(tabla);
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, 14, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Alumno");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 5, 5, 5);
        BajaAlergias.add(label1, gbc);
        cb_alumnos = new JComboBox();
        Font cb_alumnosFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, 14, cb_alumnos.getFont());
        if (cb_alumnosFont != null) cb_alumnos.setFont(cb_alumnosFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        BajaAlergias.add(cb_alumnos, gbc);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, 14, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Alergias");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.insets = new Insets(5, 5, 5, 5);
        BajaAlergias.add(label2, gbc);
        cb_alergias = new JComboBox();
        Font cb_alergiasFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, 14, cb_alergias.getFont());
        if (cb_alergiasFont != null) cb_alergias.setFont(cb_alergiasFont);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.insets = new Insets(5, 5, 5, 5);
        BajaAlergias.add(cb_alergias, gbc);
        btn_baja = new JButton();
        Font btn_bajaFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, 14, btn_baja.getFont());
        if (btn_bajaFont != null) btn_baja.setFont(btn_bajaFont);
        btn_baja.setText("Quitar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(5, 5, 5, 5);
        BajaAlergias.add(btn_baja, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return BajaAlergias;
    }

}
