package components;

import javax.swing.*;
import java.awt.*;

public class FormularioTutores extends JPanel {


    public JTextField tf_rfc;
    public JTextField tf_nombre;
    public JTextField tf_apellidoPat;
    public JTextField tf_apellidoMat;
    public JTextField tf_telefono;
    public JPanel Tutores;
    public JButton btn_registrar;
    public JTextField tf_trabajo;

    public FormularioTutores() {

    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Tutores = new JPanel();
        Tutores.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("RFC");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Tutores.add(label1, gbc);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("Nombre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Tutores.add(label2, gbc);
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Apellido Paterno");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Tutores.add(label3, gbc);
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Apellido Materno");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Tutores.add(label4, gbc);
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setText("Teléfono");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Tutores.add(label5, gbc);
        tf_rfc = new JTextField();
        Font tf_rfcFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_rfc.getFont());
        if (tf_rfcFont != null) tf_rfc.setFont(tf_rfcFont);
        tf_rfc.setMinimumSize(new Dimension(120, 26));
        tf_rfc.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Tutores.add(tf_rfc, gbc);
        tf_nombre = new JTextField();
        Font tf_nombreFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_nombre.getFont());
        if (tf_nombreFont != null) tf_nombre.setFont(tf_nombreFont);
        tf_nombre.setMinimumSize(new Dimension(120, 26));
        tf_nombre.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Tutores.add(tf_nombre, gbc);
        tf_apellidoPat = new JTextField();
        Font tf_apellidoPatFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_apellidoPat.getFont());
        if (tf_apellidoPatFont != null) tf_apellidoPat.setFont(tf_apellidoPatFont);
        tf_apellidoPat.setMinimumSize(new Dimension(120, 26));
        tf_apellidoPat.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Tutores.add(tf_apellidoPat, gbc);
        tf_apellidoMat = new JTextField();
        Font tf_apellidoMatFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_apellidoMat.getFont());
        if (tf_apellidoMatFont != null) tf_apellidoMat.setFont(tf_apellidoMatFont);
        tf_apellidoMat.setMinimumSize(new Dimension(120, 26));
        tf_apellidoMat.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Tutores.add(tf_apellidoMat, gbc);
        tf_telefono = new JTextField();
        Font tf_telefonoFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_telefono.getFont());
        if (tf_telefonoFont != null) tf_telefono.setFont(tf_telefonoFont);
        tf_telefono.setMinimumSize(new Dimension(120, 26));
        tf_telefono.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Tutores.add(tf_telefono, gbc);
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 18, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setText("Registro de tutores");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(0, 0, 10, 0);
        Tutores.add(label6, gbc);
        btn_registrar = new JButton();
        Font btn_registrarFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, btn_registrar.getFont());
        if (btn_registrarFont != null) btn_registrar.setFont(btn_registrarFont);
        btn_registrar.setText("Registrar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(20, 0, 0, 0);
        Tutores.add(btn_registrar, gbc);
        final JLabel label7 = new JLabel();
        Font label7Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label7.getFont());
        if (label7Font != null) label7.setFont(label7Font);
        label7.setText("Trabajo");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        Tutores.add(label7, gbc);
        tf_trabajo = new JTextField();
        Font tf_trabajoFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_trabajo.getFont());
        if (tf_trabajoFont != null) tf_trabajo.setFont(tf_trabajoFont);
        tf_trabajo.setMinimumSize(new Dimension(120, 26));
        tf_trabajo.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Tutores.add(tf_trabajo, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Tutores;
    }

}
