package components;

import javax.swing.*;
import java.awt.*;

public class FormularioAlumno {
    public JTextField tf_noControl;
    public JTextField tf_nombre;
    public JTextField tf_apellidoPat;
    public JComboBox<Short> cb_grado;
    public JComboBox<Character> cb_grupo;
    public JComboBox<String> cb_tutores;
    public JButton btn_registrar;
    public JPanel Alumno;
    public JTextField tf_apellidoMat;

    public FormularioAlumno() {
        cb_grado.addItem((short) 1);
        cb_grado.addItem((short) 2);
        cb_grado.addItem((short) 3);
        cb_grado.addItem((short) 4);
        cb_grado.addItem((short) 5);
        cb_grado.addItem((short) 6);

        cb_grupo.addItem('A');
        cb_grupo.addItem('B');
        cb_grupo.addItem('C');
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        Alumno = new JPanel();
        Alumno.setLayout(new GridBagLayout());
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial Rounded MT Bold", Font.BOLD, 18, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        label1.setText("Registro de alumnos");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(0, 0, 10, 0);
        Alumno.add(label1, gbc);
        final JLabel label2 = new JLabel();
        Font label2Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label2.getFont());
        if (label2Font != null) label2.setFont(label2Font);
        label2.setText("No. Control");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label2, gbc);
        tf_noControl = new JTextField();
        Font tf_noControlFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_noControl.getFont());
        if (tf_noControlFont != null) tf_noControl.setFont(tf_noControlFont);
        tf_noControl.setMinimumSize(new Dimension(120, 26));
        tf_noControl.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Alumno.add(tf_noControl, gbc);
        final JLabel label3 = new JLabel();
        Font label3Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label3.getFont());
        if (label3Font != null) label3.setFont(label3Font);
        label3.setText("Nombre");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label3, gbc);
        tf_nombre = new JTextField();
        Font tf_nombreFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_nombre.getFont());
        if (tf_nombreFont != null) tf_nombre.setFont(tf_nombreFont);
        tf_nombre.setMinimumSize(new Dimension(120, 26));
        tf_nombre.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Alumno.add(tf_nombre, gbc);
        final JLabel label4 = new JLabel();
        Font label4Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label4.getFont());
        if (label4Font != null) label4.setFont(label4Font);
        label4.setText("Apellido Paterno");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label4, gbc);
        tf_apellidoPat = new JTextField();
        Font tf_apellidoPatFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_apellidoPat.getFont());
        if (tf_apellidoPatFont != null) tf_apellidoPat.setFont(tf_apellidoPatFont);
        tf_apellidoPat.setMinimumSize(new Dimension(120, 26));
        tf_apellidoPat.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Alumno.add(tf_apellidoPat, gbc);
        final JLabel label5 = new JLabel();
        Font label5Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label5.getFont());
        if (label5Font != null) label5.setFont(label5Font);
        label5.setText("Apellido Materno");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label5, gbc);
        tf_apellidoMat = new JTextField();
        Font tf_apellidoMatFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, tf_apellidoMat.getFont());
        if (tf_apellidoMatFont != null) tf_apellidoMat.setFont(tf_apellidoMatFont);
        tf_apellidoMat.setMinimumSize(new Dimension(120, 26));
        tf_apellidoMat.setPreferredSize(new Dimension(150, 26));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        gbc.insets = new Insets(5, 5, 5, 5);
        Alumno.add(tf_apellidoMat, gbc);
        final JLabel label6 = new JLabel();
        Font label6Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label6.getFont());
        if (label6Font != null) label6.setFont(label6Font);
        label6.setText("Grado");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label6, gbc);
        final JLabel label7 = new JLabel();
        Font label7Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label7.getFont());
        if (label7Font != null) label7.setFont(label7Font);
        label7.setText("Grupo");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label7, gbc);
        cb_grado = new JComboBox();
        cb_grado.setPreferredSize(new Dimension(120, 38));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        Alumno.add(cb_grado, gbc);
        cb_grupo = new JComboBox();
        cb_grupo.setPreferredSize(new Dimension(120, 38));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 7;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(5, 5, 5, 5);
        Alumno.add(cb_grupo, gbc);
        cb_tutores = new JComboBox();
        cb_tutores.setPreferredSize(new Dimension(120, 38));
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        Alumno.add(cb_tutores, gbc);
        final JLabel label8 = new JLabel();
        Font label8Font = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, label8.getFont());
        if (label8Font != null) label8.setFont(label8Font);
        label8.setText("Tutor");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        gbc.ipadx = 5;
        gbc.ipady = 5;
        Alumno.add(label8, gbc);
        btn_registrar = new JButton();
        Font btn_registrarFont = this.$$$getFont$$$("Arial Rounded MT Bold", -1, -1, btn_registrar.getFont());
        if (btn_registrarFont != null) btn_registrar.setFont(btn_registrarFont);
        btn_registrar.setText("Registrar");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 8;
        gbc.gridwidth = 2;
        gbc.insets = new Insets(20, 0, 0, 0);
        Alumno.add(btn_registrar, gbc);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return Alumno;
    }

}
